### ISSUE TITLE
Crash on startup caused by vanillafix

### ISSUE THREAD

**Issue by quentin452** [quentin452/MUP#7]
the crash occur caused by mixins.mup.modcompat.vanillafoamfix.json when vanillafix and foamfix are enabled

the crash :
```
java.lang.IllegalAccessError: La classe net/minecraftforge/fml/common/Loader accède sans autorisation au membre "package private" de la classe org/spongepowered/asm/mixin/transformer/MixinProcessor
    at net.minecraftforge.fml.common.Loader.handler$zza000$VanillaFix_1_0_10_150$beforeConstructingMods(Loader.java:1141)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

the crash occur since this commit : https://github.com/quentin452/MUP/commit/c32319879e6df7b10a50398bd968e0ee56d4e419

**Comment by quentin452** [comment]
workaround use dev build of vanillafix : https://github.com/DimensionalDevelopment/VanillaFix/releases/tag/2.0.0+beta-29-03-2021
